dealing with artifacts

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -205,14 +205,18 @@ jobs:
         echo "Submission ID: $submission_id";
         
         # Log notarization status
-        xcrun notarytool --apple-id "$APPLE_ID" --password "$APP_SPECIFIC_PASSWORD" --team-id "$TEAM_ID" log "$submission_id" logs.txt || echo "Failed to fetch logs, check submission ID.";
+        xcrun notarytool log "$submission_id" logs.txt --keychain-profile "AC_PASSWORD" || echo "Failed to fetch logs, check submission ID.";
         
         # Check for errors in the logs
-        if [ -f logs.txt ] && grep -q 'Invalid' logs.txt; then
-          echo "Notarization failed, check logs for details.";
+        if [ -f logs.txt ]; then
+          cat logs.txt
+          if grep -q 'Invalid\|error' logs.txt; then
+            echo "Notarization failed, check logs for details.";
+            exit 1;
+          fi
         else
           echo "No errors found, proceeding to staple...";
-        fi;
+        fi
         
         # Staple the ticket
         xcrun stapler staple "dist/doc-converter.app"
